window:
  dimensions:
    columns: 160
    lines: 56
  padding:
    x: 5
    y: 0

    # decorations: buttonless

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Monaco
    style: Regular
  bold:
    family: Monaco
    style: Bold
  italic:
    family: Monaco
    style: Italic
  size: 14.0
  use_thin_strokes: true
  offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true

# Colors (Ayu Mirage)
colors:
  # Default colors
  primary:
    background: '#202734'
    foreground: '#CBCCC6'

  # Normal colors
  normal:
    black: '#191E2A'
    red: '#FF3333'
    green: '#BAE67E'
    yellow: '#FFA759'
    blue: '#73D0FF'
    magenta: '#FFD580'
    cyan: '#95E6CB'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F27983'
    green: '#A6CC70'
    yellow: '#FFCC66'
    blue: '#5CCFE6'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'

cursor:
  style: Block
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

bell:
    duration: 0

key_bindings:
  - { key: Key1,      mods: Alt,          chars: "\xA9"                  }
  - { key: Key2,      mods: Alt,          chars: "\x40"                  }
  - { key: Key3,      mods: Alt,          chars: "\xA3"                  }
  - { key: Key4,      mods: Alt,          chars: "\x24"                  }
  - { key: Key5,      mods: Alt,          chars: "∞"                     }
  - { key: Key6,      mods: Alt,          chars: "\xA7"                  }
  - { key: Backslash,      mods: Alt,          chars: "\x7C"                  }
  - { key: LBracket,      mods: Alt,          chars: "\x5B"                  }
  - { key: RBracket,      mods: Alt,          chars: "\x5D"                  }
  - { key: Key0,      mods: Alt,          chars: "≈"                     }
  - { key: Minus,     mods: Alt,          chars: "\xB1"                  }
  - { key: Apostrophe,     mods: Alt,          chars: "~"                  }
  - { key: Key1,      mods: Alt|Shift,    chars: "\xA1"                  }
  - { key: Key2,      mods: Alt|Shift,    chars: "”"                     }
  - { key: Key3,      mods: Alt|Shift,    chars: "\xA5"                  }
  - { key: Key4,      mods: Alt|Shift,    chars: "\x24"                  }
  - { key: Key5,      mods: Alt|Shift,    chars: "‰"                     }
  - { key: Key6,      mods: Alt|Shift,    chars: "\xB6"                  }
  - { key: Backslash,      mods: Alt|Shift,    chars: "\x5C"                  }
  - { key: LBracket,      mods: Alt|Shift,    chars: "\x7B"                  }
  - { key: RBracket,      mods: Alt|Shift,    chars: "\x7D"                  }
  - { key: Key0,      mods: Alt|Shift,    chars: "≠"                     }
  - { key: Minus,     mods: Alt|Shift,    chars: "\xBF"                  }

# Replace the default bindings for these as the VirtualKeycodes don't match reality
  - { key: Slash,     mods: Command,      action: DecreaseFontSize       }
  - { key: Minus,     mods: Command,      action: IncreaseFontSize       }
