window:
  dimensions:
    columns: 160
    lines: 56
  padding:
    x: 5
    y: 0

    # decorations: buttonless

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  size: 14.0
  offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  # Bright colors
  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'


cursor:
  style: Block
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

bell:
    duration: 0

key_bindings:
  - { key: Key1,      mods: Alt,          chars: "\xA9"                  }
  - { key: Key2,      mods: Alt,          chars: "\x40"                  }
  - { key: Key3,      mods: Alt,          chars: "\xA3"                  }
  - { key: Key4,      mods: Alt,          chars: "\x24"                  }
  - { key: Key5,      mods: Alt,          chars: "∞"                     }
  - { key: Key6,      mods: Alt,          chars: "\xA7"                  }
  - { key: Backslash,      mods: Alt,          chars: "\x7C"                  }
  - { key: LBracket,      mods: Alt,          chars: "\x5B"                  }
  - { key: RBracket,      mods: Alt,          chars: "\x5D"                  }
  - { key: Key0,      mods: Alt,          chars: "≈"                     }
  - { key: Minus,     mods: Alt,          chars: "\xB1"                  }
  - { key: Apostrophe,     mods: Alt,          chars: "~"                  }
  - { key: Key1,      mods: Alt|Shift,    chars: "\xA1"                  }
  - { key: Key2,      mods: Alt|Shift,    chars: "”"                     }
  - { key: Key3,      mods: Alt|Shift,    chars: "\xA5"                  }
  - { key: Key4,      mods: Alt|Shift,    chars: "\x24"                  }
  - { key: Key5,      mods: Alt|Shift,    chars: "‰"                     }
  - { key: Key6,      mods: Alt|Shift,    chars: "\xB6"                  }
  - { key: Backslash,      mods: Alt|Shift,    chars: "\x5C"                  }
  - { key: LBracket,      mods: Alt|Shift,    chars: "\x7B"                  }
  - { key: RBracket,      mods: Alt|Shift,    chars: "\x7D"                  }
  - { key: Key0,      mods: Alt|Shift,    chars: "≠"                     }
  - { key: Minus,     mods: Alt|Shift,    chars: "\xBF"                  }

# Replace the default bindings for these as the VirtualKeycodes don't match reality
  - { key: Slash,     mods: Command,      action: DecreaseFontSize       }
  - { key: Minus,     mods: Command,      action: IncreaseFontSize       }
