window:
  dimensions:
    columns: 160
    lines: 56
  padding:
    x: 5
    y: 0

    # decorations: buttonless

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  size: 14.0
  offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    #bright_foreground: '0xffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  cursor:
    text: '0x44475a'
    cursor: '0xf8f8f2'

  # Selection colors
  #
  # Colors which should be used to draw the selection area. If selection
  # background is unset, selection color will be the inverse of the cell colors.
  # If only text is unset the cell text color will remain the same.
  selection:
    text: '0xf8f8f2'
    background: '0x44475a'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'

  # Bright colors
  bright:
    black:   '0x4d4d4d'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '0x14151b'
    red:     '0xff2222'
    green:   '0x1ef956'
    yellow:  '0xebf85b'
    blue:    '0x4d5b86'
    magenta: '0xff46b0'
    cyan:    '0x59dffc'
    white:   '0xe6e6d1'

cursor:
  style: Block
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

bell:
    duration: 0

key_bindings:
  - { key: Key1,      mods: Alt,          chars: "\xA9"                  }
  - { key: Key2,      mods: Alt,          chars: "\x40"                  }
  - { key: Key3,      mods: Alt,          chars: "\xA3"                  }
  - { key: Key4,      mods: Alt,          chars: "\x24"                  }
  - { key: Key5,      mods: Alt,          chars: "∞"                     }
  - { key: Key6,      mods: Alt,          chars: "\xA7"                  }
  - { key: Backslash,      mods: Alt,          chars: "\x7C"                  }
  - { key: LBracket,      mods: Alt,          chars: "\x5B"                  }
  - { key: RBracket,      mods: Alt,          chars: "\x5D"                  }
  - { key: Key0,      mods: Alt,          chars: "≈"                     }
  - { key: Minus,     mods: Alt,          chars: "\xB1"                  }
  - { key: Apostrophe,     mods: Alt,          chars: "~"                  }
  - { key: Key1,      mods: Alt|Shift,    chars: "\xA1"                  }
  - { key: Key2,      mods: Alt|Shift,    chars: "”"                     }
  - { key: Key3,      mods: Alt|Shift,    chars: "\xA5"                  }
  - { key: Key4,      mods: Alt|Shift,    chars: "\x24"                  }
  - { key: Key5,      mods: Alt|Shift,    chars: "‰"                     }
  - { key: Key6,      mods: Alt|Shift,    chars: "\xB6"                  }
  - { key: Backslash,      mods: Alt|Shift,    chars: "\x5C"                  }
  - { key: LBracket,      mods: Alt|Shift,    chars: "\x7B"                  }
  - { key: RBracket,      mods: Alt|Shift,    chars: "\x7D"                  }
  - { key: Key0,      mods: Alt|Shift,    chars: "≠"                     }
  - { key: Minus,     mods: Alt|Shift,    chars: "\xBF"                  }

# Replace the default bindings for these as the VirtualKeycodes don't match reality
  - { key: Slash,     mods: Command,      action: DecreaseFontSize       }
  - { key: Minus,     mods: Command,      action: IncreaseFontSize       }
